# Generated by Django 4.2 on 2023-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('pname', models.CharField(max_length=20)),
                ('product_quantity', models.PositiveBigIntegerField()),
                ('manufacturer', models.CharField(max_length=20)),
                ('mfd', models.DateField()),
            ],
        ),
    ]
