# Generated by Django 4.2 on 2023-04-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deatail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mob', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('loc', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('deatail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app1.deatail')),
                ('st_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=20)),
                ('fee', models.PositiveBigIntegerField()),
            ],
            bases=('app1.deatail',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('deatail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app1.deatail')),
                ('te_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('te_name', models.CharField(max_length=20)),
                ('t_pho', models.PositiveBigIntegerField()),
            ],
            bases=('app1.deatail',),
        ),
    ]
