# Generated by Django 4.2 on 2023-04-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_deatail_delete_sample_student_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deatail',
            new_name='Detail',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='deatail_ptr',
            new_name='detail_ptr',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='deatail_ptr',
            new_name='detail_ptr',
        ),
    ]
