# Generated by Django 4.2 on 2023-04-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_deatail_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='detail_ptr',
        ),
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
