# Generated by Django 4.2 on 2023-04-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_teacher_detail_ptr_alter_detail_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Deatail',
        ),
    ]
