# Generated by Django 4.2 on 2023-04-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_detail_deatail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deatail',
            new_name='Sample',
        ),
        migrations.CreateModel(
            name='Indexdb',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app1.sample',),
        ),
    ]
